apiVersion: v1
kind: Secret
metadata:
  name: wkpoule-observability-secrets
type: Opaque
stringData:
  # Collector exporter credential for Elasticsearch's native OTel ingest.
  ELASTIC_API_KEY: dmxWRHk1MEJlWkhmS3MyYXlnYlE6QVRXdHFjX0ZCckpOeTUxRWg3Sm5jQQ==
