apiVersion: v1
kind: Secret
metadata:
  name: wkpoule-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://wkpoule:changeme@postgres:5432/wkpoule
  JWT_SECRET_KEY: changeme-use-openssl-rand-hex-32
  POSTGRES_USER: wkpoule
  POSTGRES_PASSWORD: changeme
  POSTGRES_DB: wkpoule
  WEATHER_API_KEY: ""
